### PR TITLE
Feature/bump terraform provider heroku

### PR DESCRIPTION
**Pull request by marns93**
* added Heroku logo and set logo url
* bump dependencies + upgrade to v5 of terraform-provider-heroku (breaking change, see: https://github.com/heroku/terraform-provider-heroku/releases/tag/v5.0.0). Will mention this when creating new release.

### CODE REVIEW

**Review by ringods — DISMISSED** [review]
@marns93 given `app` is renamed to `appId`, this is a breaking change. Please bump the major version number of this provider when you release.

I would expect that this would lead to changes in the SDKs as well. Did you regenerate the SDKs?

**Comment by marns93** [comment]
> 

@ringods Correct, I've checked the generated SDKs and as expected, the `app` key will change to `appId`.
Generated SDKs can be found in pipeline artifacts as well: https://github.com/pulumiverse/pulumi-heroku/actions/runs/3443448350

Version will be bumped `1.0.0`.

**Comment by ringods** [comment]
@marns93 current convention for Pulumi providers is to commit the source code of the generated SDKs to the git repository. The build process generates the SDKs again and there is a step which checks that what is generated by CI is the same as committed:

https://github.com/pulumiverse/pulumi-heroku/actions/runs/3443448350/jobs/5745018908#step:17:1

Can you add the generated SDK source code to this PR?

**Comment by marns93** [comment]
> @marns93 current convention for Pulumi providers is to commit the source code of the generated SDKs to the git repository. The build process generates the SDKs again and there is a step which checks that what is generated by CI is the same as committed:
> 
> https://github.com/pulumiverse/pulumi-heroku/actions/runs/3443448350/jobs/5745018908#step:17:1
> 
> Can you add the generated SDK source code to this PR?

Thanks for the hint @ringods . Generated SDKs added in https://github.com/pulumiverse/pulumi-heroku/pull/18/commits/ef14bd0f9dea87572022707912246a0b5fc54325

**Review by ringods — APPROVED** [review]

**Pull request merged**
